### ISSUE TITLE
控件修改样式，所有同一种控件的样式都会修改

### ISSUE THREAD

**Issue by JiangWeiTao** [vincentzyc/form-design#10]
拖放后的控件修改样式，所有同一种控件的样式都会修改

**Comment by vincentzyc** [comment]
我自己试了所有控件，同一种控件也只是针对选中的控件改变样式，并不会出现你说的那种情况

**Comment by wanghaisheng** [comment]
@vincentzyc 我上个图  我理解成你把基础类控件的名字都搞成默认了
比如输入框 现在默认控件叫姓名，标签也叫姓名，我添加多个输入框组件上去，组件类型叫姓名没关系其实，但标签名称一经修改其他同步就变动了，code是今天拉的最新的
![图片](https://user-images.githubusercontent.com/2363295/69493178-9eefbd00-0ee6-11ea-856a-51b1dce80fe2.png)

**Comment by vincentzyc** [comment]
> @vincentzyc 我上个图 我理解成你把基础类控件的名字都搞成默认了
> 比如输入框 现在默认控件叫姓名，标签也叫姓名，我添加多个输入框组件上去，组件类型叫姓名没关系其实，但标签名称一经修改其他同步就变动了，code是今天拉的最新的
> ![图片](https://user-images.githubusercontent.com/2363295/69493178-9eefbd00-0ee6-11ea-856a-51b1dce80fe2.png)

感谢反馈！已修复，对象深克隆问题

**Comment by wanghaisheng** [comment]
@vincentzyc  还有个问题 一行里面怎么放两个组件 类似一行两列 一行三列的效果

**Comment by vincentzyc** [comment]
> @vincentzyc 还有个问题 一行里面怎么放两个组件 类似一行两列 一行三列的效果

这个要做多层嵌套，而且涉及到表单数据校验和提交问题，做起来比较麻烦，你可以自己研究二次开发

**Comment by wanghaisheng** [comment]
我就是做个静态页面~不是搞开发的专门 @vincentzyc

**Comment by vincentzyc** [comment]
> 我就是做个静态页面~不是搞开发的专门 @vincentzyc

目前不支持多列

**Comment by wanghaisheng** [comment]
@vincentzyc 你那个表单内容区的控件 能发个图看看 你是怎么用的嘛 我没太看懂示意图
