### ISSUE TITLE
轮播图片的宽度

### ISSUE THREAD

**Issue by wanghaisheng** [vincentzyc/form-design#11]
宽度现在是多少呢？能不能默认使用图片原始宽度或者依据设置的高度在原有宽度基础上等比缩放
现在只能设置高度
@vincentzyc

**Comment by vincentzyc** [comment]
> 宽度现在是多少呢？能不能默认使用图片原始宽度或者依据设置的高度在原有宽度基础上等比缩放
> 现在只能设置高度
> @vincentzyc

目前宽度默认100%，高度统一设置；一般轮播图都不会做动态高度的
此项目主要提供一种动态表单解决方案，如果要实际用起来的话需要后台做接口入库存储页面信息，所以肯定需要二次开发；
在二次开发的时候，相信你的很多问题都会有答案

**Comment by wanghaisheng** [comment]
![01-score-0](https://user-images.githubusercontent.com/2363295/69793960-5ac12d00-1204-11ea-9755-7046a4cf4aac.jpg)
这个100%我不是非常明白 比如我这张图片 我要把它放在白底的背景图片中（多高多宽）才能保证我上传到表单设计工具、以及最终显示出来的不会失真
@vincentzyc

**Comment by vincentzyc** [comment]
> ![01-score-0](https://user-images.githubusercontent.com/2363295/69793960-5ac12d00-1204-11ea-9755-7046a4cf4aac.jpg)
> 这个100%我不是非常明白 比如我这张图片 我要把它放在白底的背景图片中（多高多宽）才能保证我上传到表单设计工具、以及最终显示出来的不会失真
> @vincentzyc

100%是屏幕宽度，高度自己设置，会自适应屏幕宽度的；
还是那一句，在二次开发的时候，这些问题你都会有答案
