### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by wocswang** [vincentzyc/form-design#15]
你好，其实我觉得就是浏览这块弄成一个弹窗来展示，比跳转一个页面好点把，在前面拖拽完后，点击预览填写响应的东西，然后点击保存时直接把填的值传给后端

**Comment by vincentzyc** [comment]
> 你好，其实我觉得就是浏览这块弄成一个弹窗来展示，比跳转一个页面好点把，在前面拖拽完后，点击预览填写响应的东西，然后点击保存时直接把填的值传给后端

预览是跳转到form-design-h5这个项目进行页面渲染展示的。要做弹窗预览的话，可以在点预览的时候把数据传给后端入库保存，然后弹框嵌套iframe展示form-design-h5这个项目

**Comment by wocswang** [comment]
嗯，我觉的就是点击预览的时候是先看下自己弄的怎么样不满意再改改，如果满意就点击保存，把数据给后端，然后等在手机上看这个页面的时候请求后端拿过来直接渲染了，现在这样我感觉像是起了俩项目，毕竟这个东西用到项目中肯定是功能块，其实我看你这个做的很好的，最近也是在看这块呢

**Comment by vincentzyc** [comment]
> 嗯，我觉的就是点击预览的时候是先看下自己弄的怎么样不满意再改改，如果满意就点击保存，把数据给后端，然后等在手机上看这个页面的时候请求后端拿过来直接渲染了，现在这样我感觉像是起了俩项目，毕竟这个东西用到项目中肯定是功能块，其实我看你这个做的很好的，最近也是在看这块呢

确实是要起两个项目啊，后台设计页面跟前端渲染页面是分开的两个项目。
目前这种预览不需要保存入库，是通过postMessage实现的。其他建站工具的预览基本都是先保存入库再预览的。想要实现弹框不保存预览，那就要把form-design-h5这个前端渲染页面项目搬到后台

**Comment by wocswang** [comment]
这个项目如果弄成组件形式就好了

**Comment by wocswang** [comment]
你好，方便加下qq或者微信或者群什么的吗

**Comment by vincentzyc** [comment]
> 你好，方便加下qq或者微信或者群什么的吗

感谢支持！
新建了个qq交流群：1032491358
