### ISSUE TITLE
感谢作者的分享，这个自定义表单太优秀了

### ISSUE THREAD

**Issue by HuTsing** [vincentzyc/form-design#16]
如题，非常感谢作者的分享，刚好公司最近也要我做这个相关业务，发现你的项目完全符合我们的需求，于是便拿过来用了，使用的过程中也没啥大问题，就是有些细节和结构方面需要优化。

最近我正准备给你提pr呢，发现你最近也一直在更新代码，刚好今天把我要优化的地方给改了😂

最近还有啥需要优化的么，我可以顺便一块儿改了。

顺便想添加你一个联系方式，不知道可以么，如果不方便在这里公开，可以发我邮箱么
[hqyx45@qq.com](mailto:hqyx45@qq.com)

再次感谢作者的分享，谢谢

**Comment by vincentzyc** [comment]
> 如题，非常感谢作者的分享，刚好公司最近也要我做这个相关业务，发现你的项目完全符合我们的需求，于是便拿过来用了，使用的过程中也没啥大问题，就是有些细节和结构方面需要优化。
> 
> 最近我正准备给你提pr呢，发现你最近也一直在更新代码，刚好今天把我要优化的地方给改了😂
> 
> 最近还有啥需要优化的么，我可以顺便一块儿改了。
> 
> 顺便想添加你一个联系方式，不知道可以么，如果不方便在这里公开，可以发我邮箱么
> [hqyx45@qq.com](mailto:hqyx45@qq.com)
> 
> 再次感谢作者的分享，谢谢

感谢支持！
其实这个只是最基本的一个框架，公司实际开发的项目已经迭代了很多版本，好多功能都没移过来。
最近是在重构组件这一块，以支持多样式组件；新增跑马灯组件，如下图
![TIM截图20200513162834](https://user-images.githubusercontent.com/27715315/81789637-dc004800-9536-11ea-99b9-b1b7364bb135.jpg)

新建了个交流群：1032491358
