### ISSUE TITLE
删除组件的时候，没有删除的组件没有选中。。

### ISSUE THREAD

**Issue by mapan1908** [vincentzyc/form-design#6]
我看演示的可以是选中了的

**Comment by mapan1908** [comment]
就是删除后，没有选中剩下的

**Comment by mapan1908** [comment]
额，不知道为啥又好了，然后每次删除最好一个控制台有错误
"TypeError: Cannot read property 'key' of undefined"

**Comment by vincentzyc** [comment]
> 额，不知道为啥又好了，然后每次删除最好一个控制台有错误
> “TypeError：无法读取未定义的属性'key'

我这边试了下没有报错，你可以删除node_modules然后重新install试下
