### ISSUE TITLE
下载项目npm run serve启动报错

### ISSUE THREAD

**Issue by dafuchixigua** [vincentzyc/form-design#7]
![image](https://user-images.githubusercontent.com/42792604/62196071-e8ecea00-b3af-11e9-9032-32bdc4b75584.png)

**Comment by vincentzyc** [comment]
我这边试了下没问题，你升级下node版本试试

**Comment by saperliu** [comment]
我也报这个错误
node  v10.16.2
npm   6.9.0

**Comment by dafuchixigua** [comment]
node v10.16.0

**Comment by vincentzyc** [comment]
我这边能正常启动。。。
我更新了下依赖版本，可以再试试
