### ISSUE TITLE
这个项目的目标是什么呢？

### ISSUE THREAD

**Issue by archimate** [vincentzyc/form-design#8]
可以兼容其他前端的表单组件吗？比如form-create。顺便问一下，界面生成的json 在哪里，不能导出？

**Comment by vincentzyc** [comment]
目标：自动生成H5页面，一些简单的页面修改无需前端参与，运营人员自己修改即可；
不兼容其他表单组件；
json肯定要入库，为什么要导出呢？
入库之后会在另外一个项目渲染出真正的H5页面，See [form-design-h5](https://github.com/vincentzyc/form-design-h5).

**Comment by archimate** [comment]
我想配合form-create这样的组件来使用，怎么搞呢

**Comment by vincentzyc** [comment]
只能自己clone项目去改了
